version: "3.7"

services:
  postgres:
    image: postgres:12
    volumes:
      - paparazzo-db:/var/lib/postgresql/data:rw
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=mytul
    ports:
      - 5432:5432
volumes:
  mytul-postgres-db:
